.TH WLC_POINTER_GET_POSITION 3 2016-04-22 WLC "WLC API Functions"

.SH NAME

wlc_pointer_get_position \- gets the mouse pointer position

.SH SYNOPSIS
.B #include <stdio.h>

.BI "void wlc_pointer_get_position(const struct wlc_point *"out_position ");"

.SH DESCRIPTION
.BR wlc_pointer_get_position ()
is used to get the mouse pointer position on the currently focused output.

.SH RETURN VALUE
None.
