.TH WLC_EVENT_SOURCE_REMOVE 3 2016-04-22 WLC "WLC API Functions"

.SH NAME
wlc_event_source_remove \- remove an event from event loop

.SH SYNOPSIS
.B #include <wlc/wlc.h>

.BI "void wlc_event_source_remove(struct wlc_event_source *"source );

.SH DESCRIPTION
.BR wlc_event_source_remove ()
is used to remove a
.I source
from the event loop.

.SH RETURN VALUE
None.
