.TH WLC_OUTPUT_FOCUS 3 2016-04-22 WLC "WLC Output API Functions"

.SH NAME
wlc_output_focus \- focus output

.SH SYNOPSIS
.B #include <wlc/wlc.h>

.BI "void wlc_output_focus(wlc_handle "output );

.SH DESCRIPTION
.BR wlc_output_focus ()
focuses the output defined in the output handle.

.SH RETURN VALUE
None.
