# Find DRM and friends
#
# DRM_INCLUDE_DIR
# DRM_LIBRARIES
# DRM_FOUND
#
# GBM_INCLUDE_DIR
# GBM_LIBRARIES
#
# UDEV_INCLUDE_DIR
# UDEV_LIBRARIES

FIND_PATH(UDEV_INCLUDE_DIR libudev.h)

FIND_LIBRARY(UDEV_LIBRARIES NAMES udev)

FIND_PATH(GBM_INCLUDE_DIR gbm.h)

FIND_LIBRARY(GBM_LIBRARIES NAMES gbm)

FIND_PATH(DRM_INCLUDE_DIR NAMES drm.h PATH_SUFFIXES libdrm)

FIND_LIBRARY(DRM_LIBRARIES NAMES drm)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DRM DEFAULT_MSG UDEV_INCLUDE_DIR UDEV_LIBRARIES GBM_INCLUDE_DIR GBM_LIBRARIES DRM_INCLUDE_DIR DRM_LIBRARIES)

IF (DRM_FOUND)
  message(STATUS "Found udev libs: ${UDEV_LIBRARIES}")
  message(STATUS "Found udev includes: ${UDEV_INCLUDE_DIR}")
  message(STATUS "Found gbm libs: ${GBM_LIBRARIES}")
  message(STATUS "Found gbm includes: ${GBM_INCLUDE_DIR}")
  message(STATUS "Found drm includes: ${DRM_INCLUDE_DIR}")
  message(STATUS "Found drm libs: ${DRM_LIBRARIES}")
ENDIF (DRM_FOUND)
