# Find systemd
#
# SYSTEMD_INCLUDE_DIR
# SYSTEMD_LIBRARIES
# SYSTEMD_FOUND

FIND_PATH(SYSTEMD_INCLUDE_DIR systemd/sd-login.h)
FIND_LIBRARY(SYSTEMD_LIBRARIES NAMES systemd)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SYSTEMD DEFAULT_MSG SYSTEMD_INCLUDE_DIR SYSTEMD_LIBRARIES)
mark_as_advanced(SYSTEMD_INCLUDE_DIR SYSTEMD_LIBRARIES)
