# Find DRM and friends
#
# DRM_INCLUDE_DIR
# DRM_LIBRARIES
# DRM_DEFINITIONS
# DRM_FOUND
#
# GBM_INCLUDE_DIRS
# GBM_LIBRARIES
# GBM_DEFINITIONS

find_package(PkgConfig)
pkg_check_modules(PC_GBM QUIET gbm)
find_library(GBM_LIBRARIES NAMES gbm HINTS ${PC_GBM_LIBRARY_DIRS})
find_path(GBM_INCLUDE_DIRS gbm.h HINTS ${PC_GBM_INCLUDE_DIRS})

pkg_check_modules(PC_DRM QUIET libdrm)
find_library(DRM_LIBRARIES NAMES drm HINTS ${PC_DRM_LIBRARY_DIRS})
find_path(DRM_INCLUDE_DIRS NAMES drm.h PATH_SUFFIXES libdrm drm HINTS ${PC_DRM_INCLUDE_DIRS})

set(GBM_DEFINITIONS ${PC_GBM_CFLAGS_OTHER})
set(DRM_DEFINITIONS ${PC_DRM_CFLAGS_OTHER})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DRM DEFAULT_MSG GBM_INCLUDE_DIRS GBM_LIBRARIES DRM_INCLUDE_DIRS DRM_LIBRARIES)
mark_as_advanced(GBM_INCLUDE_DIRS GBM_LIBRARIES DRM_INCLUDE_DIRS DRM_LIBRARIES)
