# Find libinput
#
# LIBINPUT_INCLUDE_DIRS
# LIBINPUT_LIBRARIES
# LIBINPUT_DEFINITIONS
# LIBINPUT_FOUND

find_package(PkgConfig)
pkg_check_modules(PC_INPUT QUIET libinput)
find_library(LIBINPUT_LIBRARIES NAMES input HINTS ${PC_INPUT_LIBRARY_DIRS})
find_path(LIBINPUT_INCLUDE_DIRS libinput.h HINTS ${PC_INPUT_INCLUDE_DIRS})

set(LIBINPUT_VERSION ${PC_INPUT_VERSION})
string(REPLACE "." ";" VERSION_LIST ${PC_INPUT_VERSION})
list(GET VERSION_LIST 0 LIBINPUT_VERSION_MAJOR)
list(GET VERSION_LIST 1 LIBINPUT_VERSION_MINOR)
list(GET VERSION_LIST 2 LIBINPUT_VERSION_MICRO)

# This is compatible with libinput-version.h that exists in upstream
# but isn't in distribution (probably forgotten)
set(LIBINPUT_DEFINITIONS ${PC_INPUT_CFLAGS_OTHER}
	-DLIBINPUT_VERSION=\"${LIBINPUT_VERSION}\"
	-DLIBINPUT_VERSION_MAJOR=${LIBINPUT_VERSION_MAJOR}
	-DLIBINPUT_VERSION_MINOR=${LIBINPUT_VERSION_MINOR}
	-DLIBINPUT_VERSION_MICRO=${LIBINPUT_VERSION_MICRO})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBINPUT DEFAULT_MSG LIBINPUT_INCLUDE_DIRS LIBINPUT_LIBRARIES)
mark_as_advanced(LIBINPUT_INCLUDE_DIRS LIBINPUT_LIBRARIES)
