# Find libinput
#
# LIBINPUT_INCLUDE_DIRS
# LIBINPUT_LIBRARIES
# LIBINPUT_DEFINITIONS
# LIBINPUT_FOUND

find_package(PkgConfig)
pkg_check_modules(PC_INPUT QUIET libinput)
find_library(LIBINPUT_LIBRARIES NAMES input HINTS ${PC_INPUT_LIBRARY_DIRS})
find_path(LIBINPUT_INCLUDE_DIRS libinput.h HINTS ${PC_INPUT_INCLUDE_DIRS})

set(LIBINPUT_DEFINITIONS ${PC_INPUT_CFLAGS_OTHER})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBINPUT DEFAULT_MSG LIBINPUT_INCLUDE_DIRS LIBINPUT_LIBRARIES)
mark_as_advanced(LIBINPUT_INCLUDE_DIRS LIBINPUT_LIBRARIES)
