# Find DRM and friends
#
# DRM_INCLUDE_DIR
# DRM_LIBRARIES
# DRM_FOUND
#
# GBM_INCLUDE_DIR
# GBM_LIBRARIES

FIND_PATH(GBM_INCLUDE_DIR gbm.h)

FIND_LIBRARY(GBM_LIBRARIES NAMES gbm)

FIND_PATH(DRM_INCLUDE_DIR NAMES drm.h PATH_SUFFIXES libdrm)

FIND_LIBRARY(DRM_LIBRARIES NAMES drm)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DRM DEFAULT_MSG GBM_INCLUDE_DIR GBM_LIBRARIES DRM_INCLUDE_DIR DRM_LIBRARIES)

mark_as_advanced(GBM_INCLUDE_DIR GBM_LIBRARIES DRM_INCLUDE_DIR DRM_LIBRARIES)
