function(add_subproject name)
   if(ARGC GREATER 1)
      set(package_name ${ARGV1})
   else()
      set(package_name ${name})
   endif()

   if(TARGET ${name})
      message("Subproject ${name} already included, skipping")
   else()
      find_package(${package_name} QUIET)
      if(NOT SOURCE_${package_name} AND ${package_name}_FOUND)
         message("Found ${package_name} on system")
      else()
         message("Adding ${name} as subdirectory")
         add_subdirectory(${name} EXCLUDE_FROM_ALL)
      endif()
   endif()
endfunction()
